idade = 23
peso = 123
altura = 1.75
input(int(f'me diga a sua idade:'))
input(int(f'me diga o seu peso:'))
input(float(f'me diga a sua altura:'))
if idade >= 18:
    print('você é maior de idade.')
else:
    print('você é menor de idade.')
if peso >= 100:
    print('você está obeso! Nível 3, cuidado.')
else:
    print('está tudo ok!') 
if altura >= 1.73:
    print('você está acima da média brasileira de estatura!')
else:
    print('você está na média!')                   



